# Generated by Django 4.2.1 on 2024-05-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spokenMaterial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
