# Generated by Django 4.2.1 on 2024-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spokenMaterial', '0002_uploadedfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='summarization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
